[attendees]
insert = ["INSERT INTO Attendees (full_name) VALUES (%s);",
"SET @new_attendee_id = LAST_INSERT_ID();",
"INSERT INTO SeanceAttendees (attendee_id, seance_id) VALUES (@new_attendee_id, %s);"]

update = "UPDATE Attendees SET full_name = %s WHERE attendee_id = %s;"

delete = "DELETE FROM Attendees WHERE attendee_id = %s;"

select = "SELECT attendee_id, full_name FROM Attendees;"
select_specific = "SELECT attendee_id, full_name FROM Attendees WHERE attendee_id = %s;"


[channelings]
insert = """
INSERT INTO Channelings (medium_id, spirit_id, method_id, seance_id, is_successful, length_in_minutes)
VALUES
(
 (%s),
 (%s),
 (%s),
 (%s),
 (%s),
 (%s)
);"""

update = """UPDATE Channelings SET
medium_id = (%s)
, spirit_id = (%s)
, method_id =  (%s)
, seance_id =  (%s)
, is_successful =  (%s)
, length_in_minutes =  (%s)
WHERE channeling_id = (%s);"""

delete = "DELETE FROM Channelings  WHERE channeling_id = (%s);"

select = """ 
SELECT Channelings.channeling_id, Channelings.medium_id
, Mediums.full_name AS medium_name
, Spirits.spirit_id, Spirits.full_name AS spirit_name
, Channelings.method_id
, Methods.name AS method_name
, Seances.seance_id
, Seances.date, Locations.name AS location_name,
Channelings.is_successful, Channelings.length_in_minutes
FROM Channelings
LEFT JOIN Mediums ON Channelings.medium_id = Mediums.medium_id
LEFT JOIN Spirits ON Channelings.spirit_id = Spirits.spirit_id
LEFT JOIN Methods ON Channelings.method_id = Methods.method_id
LEFT JOIN Seances ON Channelings.seance_id = Seances.seance_id
LEFT JOIN Locations ON Seances.location_id = Locations.location_id;
"""

select_specific = """ 
SELECT Channelings.channeling_id, Channelings.medium_id
, Mediums.full_name AS medium_name
, Spirits.spirit_id, Spirits.full_name AS spirit_name
, Channelings.method_id
, Methods.name AS method_name
, Seances.seance_id
, Seances.date, Locations.name AS location_name,
Channelings.is_successful, Channelings.length_in_minutes
FROM Channelings
LEFT JOIN Mediums ON Channelings.medium_id = Mediums.medium_id
LEFT JOIN Spirits ON Channelings.spirit_id = Spirits.spirit_id
LEFT JOIN Methods ON Channelings.method_id = Methods.method_id
LEFT JOIN Seances ON Channelings.seance_id = Seances.seance_id
LEFT JOIN Locations ON Seances.location_id = Locations.location_id
WHERE Seances.seance_id = %s;
"""

[locations]
insert = """
INSERT INTO Locations (name, street_address, city, zip, state, country)
VALUES (%s, %s, %s, %s, %s, %s);
"""

update = """
UPDATE Locations
SET name = %s,
street_address = %s, 
city = %s,
zip = %s,
state = %s,
country = %s
WHERE location_id = %s;
"""

delete = "DELETE FROM Locations WHERE location_id = %s;"

select = "SELECT location_id, name, street_address, city, zip, state, country FROM Locations;"

select_minimal = "SELECT location_id, name FROM Locations;"

select_specific = """
SELECT location_id, name, street_address, city, zip, state, country
FROM Locations
WHERE location_id = %s;
"""


[mediums]
insert = "INSERT INTO Mediums (full_name) VALUES (%s);"

update = """
UPDATE Mediums
SET full_name = %s
WHERE medium_id = %s;
"""

delete = "DELETE FROM Mediums WHERE medium_id = %s;"

select = "SELECT medium_id, full_name FROM Mediums;"

select_specific = "SELECT medium_id, full_name FROM Mediums WHERE medium_id = %s;"

[methods]
insert = "INSERT INTO Methods (name, description) VALUES (%s, %s);"


update = """
UPDATE Methods 
SET name = %s,
description = %s
WHERE method_id = %s;
"""

delete = "DELETE FROM Methods WHERE method_id = %s;"

select = "SELECT method_id, name FROM Methods;"

select_detailed = "SELECT method_id, name, description FROM Methods;"

select_specific = "SELECT method_id, name, description FROM Methods WHERE method_id = %s;"

[seanceattendees]
update = """
UPDATE SeanceAttendees
SET seance_id = %s
WHERE attendee_id = %s
AND seance_id = %s;
"""

inline_update = """
UPDATE SeanceAttendees
SET seance_id = %s
, attendee_id = %s
WHERE seanceattendees_id = %s;
"""

inline_tag = """
select
seance_id
, attendee_id
from SeanceAttendees
WHERE seanceattendees_id = %s;
"""

insert = "INSERT INTO SeanceAttendees (attendee_id, seance_id) VALUES (%s, %s)"

delete = "DELETE FROM SeanceAttendees WHERE seanceattendees_id = %s;"

select = """
SELECT SeanceAttendees.seance_id, Attendees.attendee_id, Attendees.full_name, SeanceAttendees.seanceattendees_id
FROM SeanceAttendees
LEFT JOIN Attendees ON SeanceAttendees.attendee_id = Attendees.attendee_id;
"""

select_specific = """
SELECT SeanceAttendees.seance_id, Attendees.attendee_id, Attendees.full_name, SeanceAttendees.seanceattendees_id
FROM SeanceAttendees
LEFT JOIN Attendees ON SeanceAttendees.attendee_id = Attendees.attendee_id
WHERE SeanceAttendees.seance_id = %s;
"""

select_not_attended = """
SELECT Attendees.attendee_id, Attendees.full_name
FROM Attendees
WHERE attendee_id NOT IN (
SELECT Attendees.attendee_id
FROM Attendees
NNER JOIN SeanceAttendees ON Attendees.attendee_id = SeanceAttendees.attendee_id
WHERE SeanceAttendees.seance_id = %s);
"""


[seances]
insert = "INSERT INTO Seances (date, location_id) VALUES (%s, %s);"

update = """
UPDATE Seances
SET date = %s,
location_id = %s
WHERE seance_id = %s;
"""

delete = "DELETE FROM Seances WHERE seance_id = %s;"

select = """
SELECT seance_id, Locations.name, Seances.date
FROM Seances
LEFT JOIN Locations ON Seances.location_id = Locations.location_id;
"""

select_specific = """
SELECT seance_id, Locations.name, Seances.date
FROM Seances 
LEFT JOIN Locations ON Seances.location_id = Locations.location_id
WHERE Seances.seance_id = %s
"""

select_other = """
SELECT Seances.date, Locations.name, Seances.seance_id
FROM Seances
INNER JOIN Locations ON Seances.location_id = Locations.location_id
WHERE seance_id <> %s;
"""


[spirits]
insert = "INSERT INTO Spirits (full_name) VALUES (%s);"
update = "UPDATE Spirits SET full_name = (%s) WHERE spirit_id = (%s);"
delete = "DELETE FROM Spirits  WHERE spirit_id = %s;"
select = "SELECT spirit_id, full_name FROM Spirits;"

